author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /Test20220223
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - openseadragon.min.js
    - openseadragon-svg-overlay.js
    - text-annotations.js
    - viewer.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://images.readux.io/iiif/2/2qnpcn80_00000001.jpg/full/full/0/default.jpg
image_size:
  page:
    height: 7900
    width: 10400
permalink: pretty
publication_info:
  date: '2022'
  editors: []
  title: 'Effigies antiquae Romae ex vestigiis aedificiorum ruinis testimonio veterum
    auctorum fide: numismatum monumentis, aeneis, plumbaeis, saxeis, tiglinisque //
    Effigies antiqvae Romae ex vestigiis aedificiorvm rvinis'
show_annotation_author: true
source_info:
  title: 'Effigies antiquae Romae ex vestigiis aedificiorum ruinis testimonio veterum
    auctorum fide: numismatum monumentis, aeneis, plumbaeis, saxeis, tiglinisque //
    Effigies antiqvae Romae ex vestigiis aedificiorvm rvinis'
  via_readux: true
tagline: an annotated digital edition
title: 'Effigies antiquae Romae ex vestigiis aedificiorum ruinis testimonio veterum
  auctorum fide: numismatum monumentis, aeneis, plumbaeis, saxeis, tiglinisque //
  Effigies antiqvae Romae ex vestigiis aedificiorvm rvinis'
url: https://jcmundy.github.io
version: 0.7
